Repository AY2021S1-CS2103T-F13-4/tp, pull requests merged in 2020-11, with the labels that each got.

#173 Add Tags to Expired and Expiring Food List
  src/main/java/seedu/simplykitchen/ui/ExpiredFoodListCard.java
  src/main/java/seedu/simplykitchen/ui/ExpiringFoodCard.java
  src/main/resources/view/ExpiredFoodListCard.fxml
  src/main/resources/view/ExpiringFoodCard.fxml
Labels: type.Bug, type.Task

#174 Branch fix ped bugs
  docs/UserGuide.md
  docs/images/UiPopUp.png
  docs/images/addApplePieUgExample.png
  docs/images/duplicateFood.png
  src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/EditCommand.java
Labels: type.Bug, type.Task

#172 Fix bugs found in PED - General and Find command
  docs/UserGuide.md
  docs/images/findBiscuitsCatDog.png
  src/main/java/seedu/simplykitchen/MainApp.java
  src/main/java/seedu/simplykitchen/commons/util/StringUtil.java
  src/main/java/seedu/simplykitchen/logic/Logic.java
  src/main/java/seedu/simplykitchen/logic/LogicManager.java
  src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/DeleteCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/EditCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/HelpCommand.java
  src/main/java/seedu/simplykitchen/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/simplykitchen/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/simplykitchen/logic/parser/EditCommandParser.java
  src/main/java/seedu/simplykitchen/logic/parser/FindCommandParser.java
  src/main/java/seedu/simplykitchen/model/Model.java
  src/main/java/seedu/simplykitchen/model/ModelManager.java
  src/main/java/seedu/simplykitchen/model/food/ExpiryDateSearchPredicate.java
  src/main/java/seedu/simplykitchen/model/food/Food.java
  src/main/java/seedu/simplykitchen/ui/ExpiredFoodListPanel.java
  src/main/java/seedu/simplykitchen/ui/ExpiredFoodWindow.java
  src/main/java/seedu/simplykitchen/ui/FoodCard.java
  src/main/java/seedu/simplykitchen/ui/MainWindow.java
  src/test/java/seedu/simplykitchen/logic/commands/AddCommandTest.java
  src/test/java/seedu/simplykitchen/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/simplykitchen/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/simplykitchen/logic/parser/ChangeQuantityCommandParserTest.java
  src/test/java/seedu/simplykitchen/logic/parser/EditCommandParserTest.java
Labels: type.Bug, type.Task

#179 Update DG - User stories and Ui component
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task

#182 Update DG with TOC, back to top buttons and links in Introduction
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#181 Foods in Expired and Expiring Lists are sorted by Description if same Expiry
  src/main/java/seedu/simplykitchen/model/ModelManager.java
  src/main/java/seedu/simplykitchen/model/util/ComparatorUtil.java
Labels: type.Bug

#186 Update PPP - Jonah
  docs/images/SimplyKitchenPPP.png
  docs/team/jonahtanjz.md
Labels: type.Task

#187 Add PPP draft - Song Yi
  docs/team/songyi.md
Labels: type.Task

#188 Update PPP - Cheng Hin
  docs/team/bchenghi.md
Labels: type.Task

#189 Update Project Portfolio Page - Sagar
  docs/team/sagarsureka.md
Labels: type.Task

#200 Update docs and restrict quantity unit length
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  src/main/java/seedu/simplykitchen/model/food/Description.java
  src/main/java/seedu/simplykitchen/model/food/Quantity.java
  src/main/java/seedu/simplykitchen/model/tag/Tag.java
  src/test/java/seedu/simplykitchen/model/food/QuantityTest.java
Labels: type.Task

#210 Update glossaries and add numberings to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#213 Update quick start
  docs/UserGuide.md
Labels: type.Task

#222 Update PPP formatting
  docs/team/bchenghi.md
  docs/team/jonahtanjz.md
  docs/team/rolandyuwy.md
  docs/team/sagarsureka.md
  src/main/java/seedu/simplykitchen/model/ModelManager.java
  src/main/java/seedu/simplykitchen/model/food/Priority.java
Labels: type.Task

#232 Add page breaks and fix back to top for docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#235 Add extra lines to UG after page break
  docs/UserGuide.md
Labels: type.Task
