Repository AY2021S1-CS2103T-F13-4/tp, pull requests merged in 2020-10, with the labels that each got.

#90 Add quantity field to the food model
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/EditCommand.java
  src/main/java/seedu/simplykitchen/logic/parser/AddCommandParser.java
  src/main/java/seedu/simplykitchen/logic/parser/CliSyntax.java
  src/main/java/seedu/simplykitchen/logic/parser/EditCommandParser.java
  src/main/java/seedu/simplykitchen/logic/parser/ParserUtil.java
  src/main/java/seedu/simplykitchen/model/food/Food.java
  src/main/java/seedu/simplykitchen/model/food/Quantity.java
  src/main/java/seedu/simplykitchen/model/util/SampleDataUtil.java
  src/main/java/seedu/simplykitchen/storage/JsonAdaptedFood.java
  src/main/java/seedu/simplykitchen/ui/FoodCard.java
  src/main/resources/view/FoodListCard.fxml
  src/test/data/JsonSerializableFoodInventoryTest/duplicateFoodInventory.json
  src/test/data/JsonSerializableFoodInventoryTest/typicalFoodInventory.json
  src/test/java/seedu/simplykitchen/logic/LogicManagerTest.java
  src/test/java/seedu/simplykitchen/logic/commands/CommandTestUtil.java
  src/test/java/seedu/simplykitchen/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/simplykitchen/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/simplykitchen/logic/parser/ParserUtilTest.java
  src/test/java/seedu/simplykitchen/model/food/FoodTest.java
  src/test/java/seedu/simplykitchen/model/food/QuantityTest.java
  src/test/java/seedu/simplykitchen/storage/JsonAdaptedFoodTest.java
  src/test/java/seedu/simplykitchen/testutil/EditFoodDescriptorBuilder.java
  src/test/java/seedu/simplykitchen/testutil/FoodBuilder.java
  src/test/java/seedu/simplykitchen/testutil/FoodUtil.java
Labels: priority.High, type.Task

#87 Add Undo and Redo commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/simplykitchen/MainApp.java
  src/main/java/seedu/simplykitchen/commons/util/InvalidationListenerManager.java
  src/main/java/seedu/simplykitchen/logic/LogicManager.java
  src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/ClearCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/DeleteCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/EditCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/RedoCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/UndoCommand.java
  src/main/java/seedu/simplykitchen/logic/parser/FoodInventoryParser.java
  src/main/java/seedu/simplykitchen/model/FoodInventory.java
  src/main/java/seedu/simplykitchen/model/Model.java
  src/main/java/seedu/simplykitchen/model/ModelManager.java
  src/main/java/seedu/simplykitchen/model/ReadOnlyFoodInventory.java
  src/main/java/seedu/simplykitchen/model/VersionedFoodInventory.java
  src/test/java/seedu/simplykitchen/commons/util/InvalidationListenerManagerTest.java
  src/test/java/seedu/simplykitchen/logic/LogicManagerTest.java
  src/test/java/seedu/simplykitchen/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/simplykitchen/logic/commands/AddCommandTest.java
  src/test/java/seedu/simplykitchen/logic/commands/ClearCommandTest.java
  src/test/java/seedu/simplykitchen/logic/commands/CommandTestUtil.java
  src/test/java/seedu/simplykitchen/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/simplykitchen/logic/commands/EditCommandTest.java
  src/test/java/seedu/simplykitchen/logic/commands/RedoCommandTest.java
  src/test/java/seedu/simplykitchen/logic/commands/UndoCommandTest.java
  src/test/java/seedu/simplykitchen/model/FoodInventoryTest.java
  src/test/java/seedu/simplykitchen/model/VersionedFoodInventoryTest.java
Labels: priority.Medium, type.Task

#95 Update DG - Sort Command
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#83 Update Find Command
  src/main/java/seedu/simplykitchen/logic/commands/FindCommand.java
  src/main/java/seedu/simplykitchen/logic/parser/FindCommandParser.java
  src/main/java/seedu/simplykitchen/model/food/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/simplykitchen/model/food/ExpiryDateSearchPredicate.java
  src/main/java/seedu/simplykitchen/model/food/PrioritySearchPredicate.java
  src/main/java/seedu/simplykitchen/model/tag/TagSearchPredicate.java
  src/test/data/JsonSerializableFoodInventoryTest/typicalFoodInventory.json
  src/test/java/seedu/simplykitchen/logic/commands/FindCommandTest.java
  src/test/java/seedu/simplykitchen/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/simplykitchen/logic/parser/FoodInventoryParserTest.java
  src/test/java/seedu/simplykitchen/model/food/ExpiryDateSearchPredicateTest.java
  src/test/java/seedu/simplykitchen/model/food/PrioritySearchPredicateTest.java
  src/test/java/seedu/simplykitchen/model/tag/TagSearchPredicateTest.java
  src/test/java/seedu/simplykitchen/testutil/TypicalFood.java
Labels: priority.High, type.Task

#91 Add Sort Command
  src/main/java/seedu/simplykitchen/logic/commands/EditCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/FindCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/ListCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/SortExpiryCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/SortPriorityCommand.java
  src/main/java/seedu/simplykitchen/logic/parser/FoodInventoryParser.java
  src/main/java/seedu/simplykitchen/model/Model.java
  src/main/java/seedu/simplykitchen/model/ModelManager.java
  src/main/java/seedu/simplykitchen/model/food/ExpiryDate.java
  src/main/java/seedu/simplykitchen/model/food/Priority.java
  src/main/java/seedu/simplykitchen/model/util/ComparatorUtil.java
  src/test/java/seedu/simplykitchen/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#86 Update UG - Find command
  docs/UserGuide.md
  docs/images/findAppleTunaResult.png
  docs/images/findBiscuitsCatDog.png
Labels: priority.High, type.Task

#96 Update DG - Find command
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/FindClassDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindClassDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: priority.High, type.Task

#97 Add change quantity command functionality
  src/main/java/seedu/simplykitchen/commons/util/StringUtil.java
  src/main/java/seedu/simplykitchen/logic/commands/ChangeQuantityCommand.java
  src/main/java/seedu/simplykitchen/logic/parser/ChangeQuantityCommandParser.java
  src/main/java/seedu/simplykitchen/logic/parser/CliSyntax.java
  src/main/java/seedu/simplykitchen/logic/parser/FoodInventoryParser.java
  src/main/java/seedu/simplykitchen/logic/parser/ParserUtil.java
  src/main/java/seedu/simplykitchen/model/food/Food.java
  src/main/java/seedu/simplykitchen/model/food/Quantity.java
  src/test/java/seedu/simplykitchen/commons/util/StringUtilTest.java
  src/test/java/seedu/simplykitchen/logic/commands/ChangeQuantityCommandTest.java
  src/test/java/seedu/simplykitchen/logic/commands/CommandTestUtil.java
  src/test/java/seedu/simplykitchen/logic/commands/FindCommandTest.java
  src/test/java/seedu/simplykitchen/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/simplykitchen/logic/parser/ChangeQuantityCommandParserTest.java
  src/test/java/seedu/simplykitchen/logic/parser/FoodInventoryParserTest.java
  src/test/java/seedu/simplykitchen/logic/parser/ParserUtilTest.java
  src/test/java/seedu/simplykitchen/testutil/EditFoodDescriptorBuilder.java
  src/test/java/seedu/simplykitchen/testutil/FoodUtil.java
  src/test/java/seedu/simplykitchen/testutil/TypicalFood.java
Labels: priority.High, type.Task

#100 Customise gui
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/simplykitchen/logic/Logic.java
  src/main/java/seedu/simplykitchen/logic/LogicManager.java
  src/main/java/seedu/simplykitchen/model/Model.java
  src/main/java/seedu/simplykitchen/model/ModelManager.java
  src/main/java/seedu/simplykitchen/ui/ExpiringFoodCard.java
  src/main/java/seedu/simplykitchen/ui/ExpiringFoodListPanel.java
  src/main/java/seedu/simplykitchen/ui/MainWindow.java
  src/main/resources/view/ExpiringFoodCard.fxml
  src/main/resources/view/ExpiringFoodListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/simplykitchen/logic/LogicManagerTest.java
  src/test/java/seedu/simplykitchen/logic/commands/AddCommandTest.java
  src/test/java/seedu/simplykitchen/model/ModelManagerTest.java
Labels: type.Task

#107 Fix Duplicate Food Issue
  src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java
  src/main/java/seedu/simplykitchen/logic/commands/EditCommand.java
  src/main/java/seedu/simplykitchen/model/food/Food.java
  src/test/data/JsonSerializableFoodInventoryTest/duplicateFoodInventory.json
  src/test/data/JsonSerializableFoodInventoryTest/typicalFoodInventory.json
  src/test/java/seedu/simplykitchen/model/FoodInventoryTest.java
  src/test/java/seedu/simplykitchen/model/food/FoodTest.java
  src/test/java/seedu/simplykitchen/model/food/UniqueFoodListTest.java
Labels: type.Bug

#101 Fix bugs relating to expiry date and change quantity command
  src/main/java/seedu/simplykitchen/logic/commands/ChangeQuantityCommand.java
  src/main/java/seedu/simplykitchen/model/food/ExpiryDate.java
  src/main/java/seedu/simplykitchen/model/food/Food.java
  src/main/java/seedu/simplykitchen/model/food/Quantity.java
  src/test/java/seedu/simplykitchen/logic/commands/ChangeQuantityCommandTest.java
  src/test/java/seedu/simplykitchen/logic/commands/FindCommandTest.java
  src/test/java/seedu/simplykitchen/logic/parser/FindCommandParserTest.java
Labels: type.Bug

#115 Add placeholder text for ListView
  src/main/java/seedu/simplykitchen/ui/ExpiringFoodListPanel.java
  src/main/java/seedu/simplykitchen/ui/FoodListPanel.java
Labels: type.Task

#125 Update UG - Expired command and duplicate food items
  docs/UserGuide.md
  docs/images/expiredPopup.png
Labels: type.Task

#129 Add expiry label
  src/main/java/seedu/simplykitchen/ui/FoodCard.java
  src/main/java/seedu/simplykitchen/ui/FoodListPanel.java
  src/main/resources/view/FoodListCard.fxml
Labels: type.Enhancement

#131 Update UG with Command Benefits
  docs/UserGuide.md
Labels: type.Task

#170 Change GUI colour scheme
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement
